services:
  backend-widget:        # <--- Manca il nome del servizio
    build: .           # <--- Punto (.) indica che il Dockerfile è nella stessa cartella
    ports:
      - "53140:53140"  # <--- Mappa la porta dell'host a quella del container
    env_file:
      - .env
    restart: always
